# Generated by Django 4.2.5 on 2023-10-24 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0042_hoadonthanhtoan_menus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 11, 43, 41, 470895)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='don_gia',
            field=models.FloatField(unique=True),
        ),
    ]
