# Generated by Django 4.2.5 on 2023-11-02 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0045_alter_hoadoncoctien_ds_dat_ban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadoncoctien',
            name='ngay_thanh_toan',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
