# Generated by Django 4.2.5 on 2023-11-02 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0048_rename_menus_dsdatban_menuss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsdatban',
            old_name='menuss',
            new_name='menus',
        ),
    ]
