# Generated by Django 4.2.5 on 2023-11-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0053_remove_hoadonthanhtoan_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadonthanhtoan',
            name='menus',
            field=models.ManyToManyField(related_name='ds_mon_an', to='lagu.menu'),
        ),
    ]
