# Generated by Django 4.2.5 on 2023-11-02 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0054_hoadonthanhtoan_menus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoadonthanhtoan',
            name='menus',
        ),
    ]
