# Generated by Django 4.2.5 on 2023-11-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0055_remove_hoadonthanhtoan_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ho_ten',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
