# Generated by Django 4.2.5 on 2023-11-16 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0057_remove_user_ho_ten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsdatban',
            name='menus',
        ),
    ]
