# Generated by Django 4.2.5 on 2023-11-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0058_remove_dsdatban_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsdatban',
            name='menus',
            field=models.ManyToManyField(through='lagu.DsOrder', to='lagu.menu'),
        ),
    ]
