# Generated by Django 4.2.5 on 2023-11-16 02:13

from django.db import migrations



def update_menus(apps, schema_editor):
    DsDatBan = apps.get_model('lagu', 'DsDatBan')


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0059_dsdatban_menus'),
    ]

    operations = [
        migrations.RunPython(update_menus),
    ]
