# Generated by Django 4.2.5 on 2023-11-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0060_auto_20231116_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('unit', models.IntegerField(max_length=100)),
                ('describe', models.CharField(max_length=255)),
            ],
        ),
    ]
