# Generated by Django 4.2.5 on 2023-11-16 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0063_rename_role_rule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsdatban',
            old_name='menus',
            new_name='danh_sach_menu',
        ),
    ]
