# Generated by Django 4.2.5 on 2023-11-16 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0064_rename_menus_dsdatban_danh_sach_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsdatban',
            old_name='danh_sach_menu',
            new_name='menus',
        ),
    ]
