# Generated by Django 4.2.5 on 2023-11-16 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0065_rename_danh_sach_menu_dsdatban_menus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
