# Generated by Django 4.2.5 on 2023-11-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0068_manage'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_actived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('actived', models.CharField(max_length=255)),
            ],
        ),
    ]
