# Generated by Django 4.2.5 on 2023-11-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagu', '0069_list_actived'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_actived',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('cancel', 'Cancel'), ('failed', 'Failed'), ('not_allow', 'Not Allow')], default='failed', max_length=50),
        ),
    ]
